version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    command: redis-server --bind 0.0.0.0

networks:
  mynetwork:
    driver: bridge